### ISSUE TITLE
Latest PDFs not opening

### ISSUE THREAD

**Issue by johndave8116** [JonnyFox/angular-pdf-forms#1]
1. does your angular-pdf-forms need Acrobat reader to show the pdf or render it in browsers?
we have some pdfs that are opening in latest version of Acrobat Reader software only.
those pdfs are not opening in the Browser and as well as in your ng-pdf viewer plugin as well.

let us know what is the issue?

Is your plugin dependant on browser?

**Comment by JonnyFox** [comment]
Hi @johndave8116,

this solution uses `pdfjs` as "core library" -> thus you should point to [its documentation](https://mozilla.github.io/pdf.js/) to see if your PDF types are supported.

Regards, J

**Comment by xts-velkumars** [comment]
@johndave8116 have you done ?
